In [1]:
import requests
import csv
import pandas as pd
import feedparser
import re

In [2]:
file = open("newfeed.csv","a",encoding="utf-8")
writer = csv.writer(file)
#writer.writerow(["Title","Description","Link","Year","Month"])
feed = open("Url.txt","r")
urls = feed.read()
urls = urls.split("\n")
df = pd.DataFrame(columns=["Title","Description","Link","Year","Month"])
item_dicts = {}
for url in urls:

    try:    
            f = feedparser.parse(url)
    except Exception as e:
            print('Could not parse the xml: ', url)
            print(e)
    for item in f.entries:
        r = re.compile(r"<[^>]*>")
        try:
            items_dicts = {'Title':item.title,'Description':r.sub(r"",item.summary),'Link':item.link,'Year':item.published_parsed[0],'Month':item.published_parsed[1]}
        except:
            pass
      
        f = csv.DictWriter(file, items_dicts.keys())
        f.writerow(items_dicts)

In [3]:
df = pd.read_csv("newfeed3.csv")

In [4]:
df

,Title,Description,Link,Year,Month
0,A brief introduction to Multilevel Modelling,This article was published as a part of the Da...,https://www.analyticsvidhya.com/blog/2022/01/a...,2022,1
1,Image Classification using Machine Learning,This article was published as a part of the Da...,https://www.analyticsvidhya.com/blog/2022/01/i...,2022,1
2,Log Parsing using Regular Expressions and Scal...,This article was published as a part of the Da...,https://www.analyticsvidhya.com/blog/2022/01/l...,2022,1
3,Complete Guide on Rest API with Python and Flask,This article was published as a part of the Da...,https://www.analyticsvidhya.com/blog/2022/01/r...,2022,1
4,SQL: A Full Fledged Guide from Basics to Advan...,This article was published as a part of the Da...,https://www.analyticsvidhya.com/blog/2022/01/l...,2022,1
...,...,...,...,...,...
8120,New Student Interviews: Zhanna Zhanabekova,"The new semester has just begun, and with that...",https://cds.nyu.edu/news/%relationship%/new-st...,2016,9
8121,New Student Interviews: Eduardo Fierro Farah,"The new semester has just begun, and with that...",https://cds.nyu.edu/news/%relationship%/studen...,2016,9
8122,New Student Interviews: Maya Bidanda,"The new semester has just begun, and with that...",https://cds.nyu.edu/news/%relationship%/new-st...,2016,9
8123,PwC Comes to CDS,One of the most compelling reasons to enter in...,https://cds.nyu.edu/news/%relationship%/pwc-co...,2016,9
8124,How Effective are Neural Networks for Object R...,"A few weeks ago, The New Yorker magazine publi...",https://cds.nyu.edu/news/%relationship%/effect...,2016,9